smaato/ui-framework

src/guide/components/navigation/NavItem.jsx
src/guide/components/navigation/Navigation.jsx
src/guide/components/navigation/_navigation.scss
src/guide/index.js
src/guide/index.scss
src/guide/views/AppView.jsx
src/guide/views/home/HomeView.jsx
src/guide/views/home/_homeView.scss

[BT-652]: Improve Home page and Navigation.

---

src/framework/addOnControl/AddOnControl.jsx
src/framework/addOnControl/label/AddOnLabel.jsx
src/framework/appHeader/title/AppTitleContainer.jsx
src/framework/baseDropdown/BaseDropdownOption.jsx
src/framework/body/Body.jsx
src/framework/body/BodyPanel.jsx
src/framework/body/BodyPanelItem.jsx
src/framework/button/Button.jsx
src/framework/filtersControl/filtersDropdown/FiltersDropdown.jsx
src/framework/grid/controls/GridControls.jsx
src/framework/grid/header/GridHeaderSortableCell.jsx
src/framework/grid/stickyGrid/StickyGrid.jsx
src/framework/kpi/Kpi.jsx
src/framework/label/Label.jsx
src/framework/label/SubLabel.jsx
src/framework/labeledField/LabeledField.jsx
src/framework/link/Link.jsx
src/framework/modal/ModalBody.jsx
src/framework/modal/confirmation/ModalConfirmationBody.jsx
src/framework/modal/header/ModalHeader.jsx
src/framework/modal/overlay/ModalOverlay.jsx
src/framework/modal/stack/ModalStack.jsx
src/framework/organizationSwitcher/OrganizationSwitcher.jsx
src/framework/pickedList/PickedListItem.jsx
src/framework/pickedSummary/PickedSummary.jsx
src/framework/summaryControl/SummaryControl.jsx
src/framework/text/DescriptionText.jsx
src/framework/text/Heading.jsx
src/framework/text/Text.jsx
src/framework/verticalLayout/VerticalLayout.jsx

There's no advantage to restricting children type.

[BT-655]: Convert all children props to PropType.any.

---

src/framework/modal/stack/_modalStack.scss
src/guide/views/dropdown/DropdownExample.jsx
src/guide/views/modal/ModalExample.jsx

[BT-656]: Fix ModalStack so that it doesn't crop overflowing content.

---

src/framework/body/_body.scss
src/framework/link/Link.jsx
src/framework/link/Link.spec.jsx
src/guide/views/link/LinkExample.jsx

- reusing background-color for body
- added isTargetBlank prop to link + example

[BT-658] Adjust components for InactiveUserView

---

src/framework/grid/_index.scss
src/framework/grid/body/_gridBodyCell.scss
src/framework/grid/body/_gridRow.scss
src/framework/grid/footer/_gridFooterCell.scss
src/framework/grid/header/_gridHeader.scss
src/framework/grid/stickyGrid/_stickyGrid.scss
src/framework/pickedSummary/_pickedSummary.scss
src/guide/views/grid/GridExample.jsx

- Improved consistency of grid styles and a little cleanup
- Included max-width for body cells
- Adjusted flex of PickedSummary label to avoid a shrinking icon when label is truncated

[BT-694]: Limited width for grid body cells

---

src/framework/appHeader/_appHeader.scss
src/framework/global/_body.scss
src/framework/viewHeader/_viewHeader.scss

* Padding of AppHeader and ViewHeader components isn't removed on screens wider then 1320px

Consistent header padding for all screens

---

src/framework/appHeader/_appHeader.scss
src/framework/viewHeader/_viewHeader.scss

Padding has to be on the liner, not on the main element.

Fixed header paddings

---

package.json
src/framework/modal/stack/ModalStack.jsx
src/framework/modal/stack/ModalStack.spec.jsx
src/framework/modal/stack/_modalStack.scss
src/guide/views/modal/ModalExample.jsx

* ModalStack doesn't need JavaScript to calculate its dimensions anymore.

Merge for v0.17.2 release

---

package.json
src/framework/searchBox/SearchBox.jsx
src/framework/searchBox/SearchBox.spec.jsx
src/framework/services/scroll/ScrollPosition.js
src/framework/services/scroll/ScrollPosition.spec.js
src/guide/views/menu/MenuExample.jsx
src/guide/views/searchBox/SearchBoxExample.jsx

* Added defaultValue prop to SearchBox.
* Added reset method to ScrollPosition service.

Merge for v0.17.3 release

---

package.json
src/framework/button/Button.jsx
src/framework/button/_button.scss
src/framework/grid/header/_gridHeader.scss
src/framework/organizationSwitcher/_organizationSwitcherItem.scss
src/guide/views/button/ButtonExample.jsx

* Added type "LOG" to Button component.

Merge for v0.17.4 release

---

package.json

* Added type "LOG" to ModalHeader component.

Merge for v0.17.4 re-release

---

src/framework/modal/header/_modalHeader.scss

It will now take up all the available space.

[BT-830]: Adjusted styles of modal header title

---

package.json
src/framework/appHeader/account/AccountNav.jsx
src/framework/appHeader/account/_accountNav.scss
src/framework/modal/header/ModalHeader.jsx
src/framework/modal/header/_modalHeader.scss
src/guide/views/appHeader/AppHeaderExample.jsx

* Title of ModalHeader takes up all of the available width.
* Hover highlighting of AccountNav happens only when onClick prop is defined.

Merge for v0.17.5 release

---

src/framework/viewHeader/ViewHeaderNav.jsx

- exporting ACTIVE_LINK_CLASS_NAME through the component

[SDX-899] Visualize AQ Layer in Exchange Settings

---

package.json
src/framework/viewHeader/ViewHeaderNav.jsx

* ViewHeaderNav exposes active link class name.

Merge for v0.17.7 release

---

package.json
src/framework/_index.scss
src/framework/framework.js
src/framework/framework.spec.js
src/framework/grid/body/GridFakeRow.spec.jsx
src/framework/grid/body/GridRow.spec.jsx
src/framework/horizontalLine/HorizontalLine.jsx
src/framework/horizontalLine/HorizontalLine.spec.jsx
src/framework/horizontalLine/_horizontalLine.scss
src/framework/horizontalLine/_index.scss
src/framework/text/Heading.jsx
src/framework/text/Heading.spec.jsx
src/framework/text/_heading.scss
src/guide/services/route/Route.js
src/guide/views/horizontalLine/HorizontalLineExample.jsx
src/guide/views/text/TextExample.jsx

- upgraded karma-phantomjs-launcher to make tests runnable again (sierraOS bug)
- adjusted failing test cases due to upgrade
- added size to heading, default is large (non-breaking)
- added small heading
- added horizontal line component

[SDX-1034] Create new Heading and Horizontal Line component

---

src/framework/_index.scss
src/framework/framework.js
src/framework/framework.spec.js
src/framework/global/_body.scss
src/framework/leftFixedLayout/LeftFixedLayout.jsx
src/framework/leftFixedLayout/LeftFixedLayout.spec.jsx
src/framework/leftFixedLayout/_index.scss
src/framework/leftFixedLayout/_leftFixedLayout.scss
src/guide/services/route/Route.js
src/guide/views/leftFixedLayout/LeftFixedLayoutExample.jsx

- added LeftFixedLayout
- added viewport_bigScreen

[SDX-1040] Create layout component

---

src/framework/base/box/BaseBox.jsx
src/framework/base/box/BaseBox.spec.jsx
src/framework/base/box/_index.scss
src/framework/box/Box.jsx
src/framework/box/_box.scss
src/guide/views/box/BoxExample.jsx

Adds the rounded corners as a boolean prop. Please review @jenslonkowski @ahollesen

SDX-1041 Added roundedCorners prop.

---

src/framework/body/_bodyPanel.scss
src/framework/leftFixedLayout/LeftFixedLayout.jsx
src/framework/leftFixedLayout/_leftFixedLayout.scss
src/guide/views/body/BodyExample.jsx

- adjusted leftFixedLayout to use sticky
- fixed bodyPanel border-top for isTopFlush

[SDX-1028] Integrate UI components in inventory discovery view

---

src/framework/chart/LineChart.jsx
src/guide/views/chart/ChartExample.jsx

1. Y axis can now also be on the left.
2. Line dots closest to mouse cursor are always shown.

[SDX-1097] LineChart improvements

---

src/framework/pickedList/PickedListItem.jsx
src/framework/pickedList/PickedListItem.spec.jsx
src/framework/pickedList/_pickedListItem.scss
src/guide/views/pickedList/PickedListExample.jsx

[SDX-947] Show the IDs in the targeting section as well

---

package.json
src/framework/_index.scss
src/framework/framework.js
src/framework/framework.spec.js
src/framework/toggle/Toggle.jsx
src/framework/toggle/Toggle.spec.jsx
src/framework/toggle/_index.scss
src/framework/toggle/_toggle.scss
src/guide/services/route/Route.js
src/guide/views/toggle/ToggleExample.jsx

- added react-toggle as dependency
- added component and adjusted styling

[SDX-1099] Create toggle button component

---

src/framework/toggle/Toggle.jsx
src/framework/toggle/_toggle.scss
src/guide/views/toggle/ToggleExample.jsx

[SDX-1166] Add labels to toggle

---

src/framework/dropdown/_dropdown.scss
src/framework/dropdown/_dropdownOption.scss
src/guide/views/dropdown/DropdownExample.jsx

- adjusted styling of dropdown list

[SDX-1135] Design dropdown options

---

src/framework/filterControl/FilterControl.jsx
src/framework/filterControl/FilterControl.spec.jsx
src/framework/filterControl/FilterItem.jsx
src/framework/filterControl/FilterItem.spec.jsx
src/framework/filterControl/filterDropdown/CreateFilterFormDropdown.jsx

- review suggestions
- not all comments touched yet!

[SDX-1202] Review feedback

---

src/framework/_index.scss
src/framework/alert/Alert.jsx
src/framework/alert/Alert.spec.jsx
src/framework/alert/_alert.scss
src/framework/alert/_index.scss
src/framework/fieldMessage/_index.scss
src/framework/framework.js
src/framework/framework.spec.js
src/framework/global/_colors.scss
src/guide/services/route/Route.js
src/guide/views/alert/AlertExample.jsx

- added alert component + example

[SDX-1174] Handle error case when druid not available

---

src/framework/statusDropdown/StatusDropdown.jsx
src/framework/statusDropdown/StatusDropdown.spec.jsx
src/framework/statusDropdown/_statusDropdown.scss
src/guide/views/statusDropdown/StatusDropdownExample.jsx

[SDX-1143] Adjust Status dropdown - review feedback

---

src/framework/base/dropdown/BaseDropdown.jsx
src/framework/body/_body.scss

* Choose dropdown's direction better

[SDX-1256] No scroll when dropdown is opened v2

---

src/framework/statusDropdown/StatusDropdown.jsx
src/framework/statusDropdown/StatusDropdown.spec.jsx
src/framework/statusDropdown/_statusDropdown.scss
src/guide/views/statusDropdown/StatusDropdownExample.jsx

- added DISABLED as possible option
- preventing rendering the dropdown in case of DISABLED

[SDX-1265] Add DISABLED to StatusDropdown

---

src/framework/tooltip/Tooltip.jsx

[SDX-1389] Update tooltip component in UI framework

---

src/framework/grid/empty/GridEmptyRow.jsx
src/framework/grid/empty/GridEmptyRow.spec.jsx
src/framework/grid/empty/_gridEmptyRow.scss
src/framework/grid/empty/_index.scss
src/guide/views/grid/GridExample.jsx

- added height and message to GridEmptyRow

[SEM-46] Improve GridEmptyRow

---

src/framework/button/AlertButton.jsx
src/framework/button/AlertButton.spec.jsx
src/framework/button/Button.jsx
src/framework/button/_button.scss
src/guide/views/button/ButtonExample.jsx

[SEM-26] Create list view for mapped external inventory:

---

README.md
src/framework/_index.scss
src/framework/card/Card.jsx
src/framework/card/Card.spec.jsx
src/framework/card/_card.scss
src/framework/card/_index.scss
src/framework/framework.js
src/framework/global/_colors.scss
src/framework/label/SubLabel.jsx
src/framework/label/SubLabel.spec.jsx
src/guide/services/route/Route.js
src/guide/views/card/CardExample.jsx

Usage of new card component
```
<Card
imageSrc="http://pipsum.com/210x150.jpg"
title="This is a title"
subtitle="This is a subtitle and this is also a part of the same"
description={longDescription}
hightlightText="Highlight"
tooltipText="Tooltip"
width="210px"
height="250px"
/>
```

[Feature] New Card Component

---

README.md
src/framework/_index.scss
src/framework/cardHolder/CardHolder.jsx
src/framework/cardHolder/CardHolder.spec.jsx
src/framework/cardHolder/_cardHolder.scss
src/framework/cardHolder/_index.scss
src/framework/framework.js
src/guide/services/route/Route.js
src/guide/views/cardHolder/CardHolderExample.jsx

This pull request is blocked by https://github.com/smaato/ui-framework/pull/323
Usage of `CardHolder`
```jsx
const arr = [1, 2, 3, 4, 5, 6, 7, 8];
<CardHolder>
{arr.map(i => <Card
key={i}
imageSrc="http://pipsum.com/210x150.jpg"
title={`Card ${i}`}
subtitle="This is a subtitle and this is also a part of the same"
description={longDescription}
hightlightText={`Highlight ${i}`}
tooltipText={`Tooltip ${i}`}
/>)}
</CardHolder>
```
Uses `CSS grid` feature to align the cards inside card holder.
Tested on latest 
- Chrome(`Version 65.0.3325.181 (Official Build) (64-bit)`)
- Firefox(`59.0.2 (64-bit)`)
- Safari(`Version 11.1 (13605.1.33.1.2)`)
on MacOS High Sierra `10.13.4`.

[Feature] Card holder component

---

src/framework/_index.scss
src/framework/accordion/Accordion.jsx
src/framework/accordion/Accordion.spec.jsx
src/framework/accordion/_accordion.scss
src/framework/accordion/_index.scss
src/framework/accordionItem/AccordionItem.jsx
src/framework/accordionItem/AccordionItem.spec.jsx
src/framework/accordionItem/_accordionItem.scss
src/framework/accordionItem/_index.scss
src/framework/framework.js
src/guide/services/route/Route.js
src/guide/views/accordion/AccordionExample.jsx

[SDX-1563] Create accordeon component:

---

package.json

Bump to v0.20.0

---

src/framework/toggle/Toggle.jsx
src/framework/toggle/Toggle.spec.jsx
src/guide/views/toggle/ToggleExample.jsx

- update uiframework with toggle, defaultChecked to checked

[SDX-1635] Multi ID insertion for larger targetings:
